server:
  port: 8080
  address: 0.0.0.0

logging:
  file:
    name: /var/log/ujenzilink/app.log
  logback:
    rolling-policy:
      file-name-pattern: /var/log/ujenzilink/app-%d{yyyy-'W'ww}.%i.log
      max-history: 52
      total-size-cap: 10GB
  level:
    root: INFO
    com.ujenzilink: DEBUG
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

spring:
  output:
    ansi:
      enabled: ALWAYS
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 10MB

  # Postgres for local
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: ${DB_DDL}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret-key: ${JWT_SECRET}

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  root-folder: ujenzilink

resend:
  api-key: ${RESEND_API_KEY}
  from-email: noreply@mail.ujenzilink.com

r2:
  account-id: ${R2_ACCOUNT_ID}
  access-key: ${R2_ACCESS_KEY}
  secret-key: ${R2_SECRET_KEY}
  bucket-name: ${R2_BUCKET_NAME}
  public-url: ${R2_PUBLIC_URL}
  endpoint: ${ENDPOINT}

folders:
  profile-pictures: profile-pictures
  post-images: posts
  project-stage-images: project-stages
  project-floor-plans: floor-plans

app:
  frontend-url: https://ujenzilink.com
  admin-api-key: musa
  report-recipient: ujenzilink@gmail.com