server:
  port: 8080
  address: 0.0.0.0

spring:
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 10MB

  # Postgres for local
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret-key: ${JWT_SECRET}

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  root-folder: ujenzilink

resend:
  api-key: ${RESEND_API_KEY}
  from-email: onboarding@resend.dev

r2:
  account-id: ${R2_ACCOUNT_ID}
  access-key: ${R2_ACCESS_KEY}
  secret-key: ${R2_SECRET_KEY}
  bucket-name: ${R2_BUCKET_NAME}
  public-url: ${R2_PUBLIC_URL}
  endpoint: ${ENDPOINT}

folders:
  profile-pictures: profile-pictures
  post-images: posts
  project-stage-images: project-stages
  project-floor-plans: floor-plans

app:
  frontend-url: http://localhost:4200