package com.ujenzilink.ujenzilink_backend.notifications.enums;

public enum NotificationType {
    // Posts
    POST_CREATED,
    POST_LIKE,
    POST_COMMENT,
    POST_COMMENT_REPLY,
    POST_COMMENT_LIKE,

    // Projects
    PROJECT_CREATED,
    PROJECT_LIKE,
    PROJECT_COMMENT,
    PROJECT_COMMENT_REPLY,
    PROJECT_COMMENT_LIKE,
    PROJECT_FOLLOW,
    PROJECT_MEMBER_ADDED,
    PROJECT_UPDATED,
    PROJECT_STAGE_UPDATE,
    PROJECT_DELETED,
    PROJECT_VISIBILITY_CHANGED,

    // Chats
    DIRECT_MESSAGE,
    GROUP_MESSAGE,
    CHAT_MENTION,

    // Authentication
    VERIFICATION_CODE,
    PASSWORD_RESET,
    SIGNUP_SUCCESS,
    SIGNIN_SUCCESS,

    // System
    SYSTEM_ANNOUNCEMENT,
    ACCOUNT_SECURITY
}
